event_create:
  path: /events/create
  controller: App\Controller\Event\EventPostController
  methods:  [POST]

event_find:
  path: /events/{id}
  controller: App\Controller\Event\EventFindController
  methods:  [GET]